build_scripts: fix 'pyside_package' does not exist
'setup.py develop', 'setup.py bdist_egg' fail on a clean checkout:

    $ python setup.py develop
    running develop
    error: error in 'egg_base' option: 'pyside_package' does not exist or is not a directory

It happens because there is no 'pyside_package' dir when 'egg_info'
is ran. Also, installing PySide from git using pip fails too. Both
pip and setuptools expect that package directory is checked into
source control.

To fix that, point setuptools to actual source directories, and only
override the directory for build_py.

Change-Id: I87b4e3707839f5804d349e1dba12d8f8258d7615
Fixes: PYSIDE-808