WIP: build_scripts: get rid of 'pyside_package' dir
'setup.py develop', 'setup.py bdist_egg' fail on a clean checkout:

    $ python setup.py develop
    running develop
    error: error in 'egg_base' option: 'pyside_package' does not exist or is not a directory

It happens because there is no 'pyside_package' dir when 'egg_info'
is ran. Also, installing PySide from git using pip fails too. Both
pip and setuptools expect that package directory is checked into
source control.

To fix that, get rid of 'pyside_package' and copy files directly
into the build dir.

Change-Id: I108ddab8233dacadd1120ac2dcb1265020e20605
Fixes: PYSIDE-808