build_scripts: get rid of 'pyside_package' dir
'setup.py develop', 'setup.py bdist_egg' fail on a clean checkout:

    $ python setup.py develop
    running develop
    error: error in 'egg_base' option: 'pyside_package' does not exist or is not a directory

It happens because there is no 'pyside_package' dir when 'egg_info'
is ran. Also, installing PySide from git using pip fails too. Both
pip and setuptools expect that package directory is checked into
source control.

To fix that, get rid of 'pyside_package' and copy files directly
into the build dir.

There is a small difference in generated eggs. After this commit,
few new files are added:

+pyside2uic/widget-plugins/__pycache__/qtdeclarative.cpython-37.pyc
+pyside2uic/widget-plugins/__pycache__/qtwebkit.cpython-37.pyc
+pyside2uic/widget-plugins/qtdeclarative.py
+pyside2uic/widget-plugins/qtwebkit.py

I'm not sure if they should be added to the package or not.

Change-Id: Ie5360a378022379ab9b4d9a47b316e0480f3ca93
Fixes: PYSIDE-808